services:
  # База данных PostgreSQL
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: techshop
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Django бэкенд — порт 8000
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      DEBUG: 1
      DATABASE_URL: postgresql://postgres:postgres@db:5432/techshop
    depends_on:
      - db

  # React фронтенд — порт 3000
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules # node_modules не перезаписываем с хоста
    depends_on:
      - backend

volumes:
  postgres_data:
